const Time = [
    {
        id: '01',
        city : "Mymensingh",
        date: "2023-03-24",
        day: "Friday",
        sehriTime: "04:41 AM",
        fazarTime: "04:47 AM",
        iftarTime: "06:18 PM",
    },
    {
        id: '02',
        city : "Mymensingh",
        date: "2023-03-25",
        day: "Saturday",
        sehriTime: "04:40 AM",
        fazarTime: "04:46 AM",
        iftarTime: "06:19 PM",
    },
    {
        id: '03',
        city : "Mymensingh",
        date: "2023-03-26",
        day: "Sunday",
        sehriTime: "04:38 AM",
        fazarTime: "04:44 AM",
        iftarTime: "06:19 PM",
    },
    {
        id: '04',
        city : "Mymensingh",
        date: "2023-03-27",
        day: "Monday",
        sehriTime: "04:37 AM",
        fazarTime: "04:43 AM",
        iftarTime: "06:20 PM",
    },
    {
        id: '05',
        city : "Mymensingh",
        date: "2023-03-28",
        day: "Tuesday",
        sehriTime: "04:36 AM",
        fazarTime: "04:42 AM",
        iftarTime: "06:20 PM",
    },
    {
        id: '06',
        city : "Mymensingh",
        date: "2023-03-29",
        day: "Wednesday",
        sehriTime: "04:35 AM",
        fazarTime: "4:41 AM",
        iftarTime: "6:21 PM",
    },
    {
        id: '07',
        city : "Mymensingh",
        date: "2023-03-30",
        day: "Thursday",
        sehriTime: "04:33 AM",
        fazarTime: "4:39 AM",
        iftarTime: "6:21 PM",
    },
    {
        id: '08',
        city : "Mymensingh",
        date: "2023-03-31",
        day: "Friday",
        sehriTime: "04:32 AM",
        fazarTime: "4:38 AM",
        iftarTime: "6:22 PM",
    },
    {
        id: '09',
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Saturday",
        sehriTime: "04:31 AM",
        fazarTime: "4:37 AM",
        iftarTime: "6:22 PM",
    },
    {
        id: '10',
        city : "Mymensingh",
        date: "2023-04-02",
        day: "Sunday",
        sehriTime: "04:30 AM",
        fazarTime: "4:36 AM",
        iftarTime: "6:23 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
    {
        id: 1,
        city : "Mymensingh",
        date: "2023-04-01",
        day: "Thursday",
        sehriTime: "04:41 AM",
        fazarTime: "4:47 AM",
        iftarTime: "6:18 PM",
    },
]

export default Time